### ISSUE TITLE
Issue with NPM Start

### ISSUE THREAD

**Issue by Vandivier** [seiyria/deck.zone#28]
Installed and ran NPM Start. Looks like it tried to fire:

1. npm run build:lang && webpack-dev-server --open --content-base src/ --inline --hot

1. mkdir -p src/decklang && npm run build:lang:map && nearleyc decklang/decklang.ne -o src/decklang/decklang.js

but the second command threw: The syntax of the command is incorrect.

npm-debug.log dump below:
-----------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle deck.zone@0.0.1~prestart: deck.zone@0.0.1
6 silly lifecycle deck.zone@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle deck.zone@0.0.1~start: deck.zone@0.0.1
8 verbose lifecycle deck.zone@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle deck.zone@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\.bin;C:\Program Files (x86)\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\John Vandivier\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\John Vandivier\AppData\Local\Programs\Python\Python35-32\;C:\Users\John Vandivier\AppData\Roaming\npm;C:\Program Files\R\R-3.2.3\bin\x64;
10 verbose lifecycle deck.zone@0.0.1~start: CWD: C:\Users\John Vandivier\Documents\GitHub\deck.zone
11 silly lifecycle deck.zone@0.0.1~start: Args: [ '/d /s /c',
11 silly lifecycle   'npm run build:lang && webpack-dev-server --open --content-base src/ --inline --hot' ]
12 silly lifecycle deck.zone@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle deck.zone@0.0.1~start: Failed to exec start script
14 verbose stack Error: deck.zone@0.0.1 start: `npm run build:lang && webpack-dev-server --open --content-base src/ --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid deck.zone@0.0.1
16 verbose cwd C:\Users\John Vandivier\Documents\GitHub\deck.zone
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error deck.zone@0.0.1 start: `npm run build:lang && webpack-dev-server --open --content-base src/ --inline --hot`
22 error Exit status 1
23 error Failed at the deck.zone@0.0.1 start script 'npm run build:lang && webpack-dev-server --open --content-base src/ --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the deck.zone package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:lang && webpack-dev-server --open --content-base src/ --inline --hot
23 error You can get their info via:
23 error     npm owner ls deck.zone
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by seiyria** [comment]
As a temporary solution, just remove the `mkdir -p` from whichever npm script has it; I intended to remove this and will do so soon.

**Comment by seiyria** [comment]
Actually, I've done this now. I had a few dependencies that needed updating and installing (not sure how they didn't get added). You'll have to npm install again. Specifically, I've updated `ng2-fontawesome` and added `ng2-vs-for`.

**Comment by seiyria** [comment]
Sorry about that mess. I did a fresh checkout, install, and npm start, and it works. Let me know if you have any other issues running it.

**Comment by Vandivier** [comment]
No worries! I hope I'm at least half as helpful as I am inconvenient.

Even after a complete repo delete, new checkout, install, start, I am still seeing the same ng2-fontawesome error.

Here's the full debug log:
----------------------------------
ERROR in ./~/ng2-fontawesome/index.js
Module parse failed: C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\ng2-fontawesome\index.js Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (5:0)
    at Parser.pp.raise (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:920:13)
    at Parser.pp.getTokenFromCode (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:2813:8)
    at Parser.pp.readToken (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:2508:15)
    at Parser.pp.nextToken (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:2500:71)
    at Parser.pp.next (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:2449:8)
    at Parser.pp.eat (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:1420:10)
    at Parser.pp.semicolon (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:1462:13)
    at Parser.pp.parseImport (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:2239:8)
    at Parser.pp.parseStatement (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:1744:60)
    at Parser.pp.parseTopLevel (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:1648:21)
 @ ./src/bootstrap.js 19:22-48

ERROR in ./~/ng2-ace/index.js
Module parse failed: C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\ng2-ace\index.js Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (5:0)
    at Parser.pp.raise (C:\Users\John Vandivier\Documents\GitHub\deck.zone\node_modules\acorn\dist\acorn.js:920:13)

**Comment by seiyria** [comment]
Really, that's strange. I'll try it on my windows desktop because I can't replicate it on OSX.

**Comment by seiyria** [comment]
Looks to be a windows-only issue so far. I'm asking around and I'll update here when I have an answer.

**Comment by seiyria** [comment]
Alright, sorry again about that. I got it working on windows. Just had to compile all of my modules. Strange, but whatever, it works now. Thanks for bringing this to my attention, and happy hacking!

**Comment by Vandivier** [comment]
Awesome - working like a charm. Thanks!
